name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, macos-latest]
        architecture: [x86_64, aarch64, armv7]
        rust: ["1.86"]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'nightly' }}

    steps:
      - uses: actions/checkout@v4

      - name: Restore cargo cache
        uses: Swatinem/rust-cache@v2
        env:
          cache-name: ci
        with:
          shared-key: ${{ matrix.os }}-${{ env.cache-name }}-${{ matrix.rust }}

      - name: MacOS Workaround
        if: matrix.os == 'macos-latest'
        run: cargo clean

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - name: Override rust toolchain
        run: rustup override set ${{ matrix.rust }}

      - name: Rustup Show
        run: rustup show

      - name: Build Debug
        run: |
          cargo build

      - name: Run tests
        run: cargo test --workspace

      - name: Run clippy
        run: |
          cargo clippy --workspace --all-features

      - name: Build Release
        run: cargo build --release

      - name: Test Install
        run: cargo install --path "./hosts-hook-cli" --force --locked

      - name: Update Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v3
        if: contains(github.ref, 'refs/tags/')
        with:
          formula-name: hostshook
          homebrew-tap: powerumc/homebrew-tap
          download-url: https://github.com/powerumc/hosts-hook/archive/${{ github.ref_name }}.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}